draw_set_font(global.font_title_2)
draw_set_color(c_lime)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text_ext_transformed(8 * global.gui_unit,2.2 * global.gui_unit,"GET IN THE",10,800,global.gui_scale,global.gui_scale,0)
draw_set_font(global.font_title)
draw_set_color(c_white)
draw_set_valign(fa_middle)
draw_text_ext_transformed(8 * global.gui_unit,2.6 * global.gui_unit,"W RMH LE",10,8000,global.gui_scale,global.gui_scale,0)
