remaining_steps = 8;
step_timer = 1
damage = 3;
victim = noone;
target_dir = -phy_rotation
max_turn = 15
targeting_arc = 360;
spread = 45
color = c_navy
chance_new_branch = 10 //percentage
new_branch_angle = 45